name = "ADNLPModels"
uuid = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
version = "0.2.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ForwardDiff = "0.9.0, 0.10.0"
NLPModels = "0.15, 0.17"
Requires = "1"
julia = "^1.3.0"

[extras]
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["NLPModelsModifiers", "NLPModelsTest", "ReverseDiff", "Test", "Zygote"]
